---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# aisrisk

<!-- badges: start -->
<!-- badges: end -->

The goal of aisrisk is to provide a repository for the workflows and code used to create a Aquatic Invasive Species (AIS) invasion risk prioritization in Idaho specifically the Nez-Perce/Clearwater and Idaho Panhandle National Forests.  

**Currently in heavy development.**

## Example

This is a preliminary output accomplished by the vignettes.  


```{r, echo=FALSE, eval=FALSE}

library(sf)
library(tidyverse)
library(resourceviz)
library(colorblindr)
library(ggtext)
library(gt)
library(patchwork)


final_stream <- read_sf('Z:/GIT/aisrisk/data/simple_features.gpkg', layer = 'nhdplus_idaho_final_together')

final_lakes <- read_sf( 'Z:/GIT/aisrisk/data/simple_features.gpkg', layer = 'waterbodies_idaho_final_together')

myColors <- c("#F0E442", "#56B4E9", "#E69F00", "#009E73")

names(myColors) <- factor(1:4)

idaho <- AOI::aoi_get(state = 'Idaho') %>% st_crop(st_transform(final_stream, st_crs(.)))

social_and_habitat_final_final <- bind_rows(final_stream, final_lakes) %>% 
  mutate(across(c(waterbody_type:mussel_proximity, p_h_model:temperature_model), ~ifelse(is.na(.x), 0, .x))) %>%
  mutate(
    summed_social = waterbody_position + waterbody_size_rec + waterbody_type + mussel_proximity,
    summed_habitat = temperature_model + p_h_model + calcium_model + hardness_model + do_model + conductivity_model
  ) %>%
  mutate(
    final_score_social = case_when(
      summed_social > 0 & summed_social <= 5 ~ 1,
      summed_social > 5 & summed_social <= 10 ~ 2,
      summed_social > 10 & summed_social <= 16 ~ 3,
      summed_social > 16 & summed_social <= 24 ~ 4,
    ),
    final_score_habitat = case_when(
      summed_habitat > 0 & summed_habitat <= 5 ~ 1,
      summed_habitat > 5 & summed_habitat <= 10 ~ 2,
      summed_habitat > 10 & summed_habitat <= 16 ~ 3,
      summed_habitat > 16 & summed_habitat <= 24 ~ 4,
    )
  ) %>%
  mutate(
    final_score = case_when(
      final_score_social==4 & final_score_habitat==4 ~ 1,
      final_score_social==4 & final_score_habitat==3 ~ 2,
      final_score_social==3& final_score_habitat==4 ~ 2,
      final_score_social==3& final_score_habitat==3 ~ 3,
      final_score_social==4& final_score_habitat==2 ~ 4,
      final_score_social==4& final_score_habitat==1 ~ 4,
      final_score_social==2& final_score_habitat==4 ~ 4,
      final_score_social==1& final_score_habitat==4 ~ 4,
      final_score_social==3& final_score_habitat==NA_real_ ~ 5,
      final_score_social==NA_real_& final_score_habitat==3 ~ 5,
      final_score_social==3& final_score_habitat==2 ~ 6,
      final_score_social==2& final_score_habitat==3 ~ 6,
      final_score_social==3& final_score_habitat==1 ~ 7,
      final_score_social==1& final_score_habitat==3 ~ 7,
      final_score_social==2& final_score_habitat==2 ~ 8,
      final_score_social==2& final_score_habitat==1 ~ 9,
      final_score_social==1& final_score_habitat==2 ~ 9,
      final_score_social==1 &final_score_habitat==1 ~ 10,
      TRUE ~ NA_real_



    )
  )

social_and_habitat_final_df_final <- social_and_habitat_final_final %>% st_drop_geometry()


final_lakes <- final_lakes %>% 
  mutate(across(c(waterbody_type:mussel_proximity, p_h_model:temperature_model), ~ifelse(is.na(.x), 0, .x))) %>%
  mutate(
    summed_social = waterbody_position + waterbody_size_rec + waterbody_type + mussel_proximity,
    summed_habitat = temperature_model + p_h_model + calcium_model + hardness_model + do_model + conductivity_model
  ) %>%
  mutate(
    final_score_social = case_when(
      summed_social > 0 & summed_social <= 5 ~ 1,
      summed_social > 5 & summed_social <= 10 ~ 2,
      summed_social > 10 & summed_social <= 16 ~ 3,
      summed_social > 16 & summed_social <= 24 ~ 4,
    ),
    final_score_habitat = case_when(
      summed_habitat > 0 & summed_habitat <= 5 ~ 1,
      summed_habitat > 5 & summed_habitat <= 10 ~ 2,
      summed_habitat > 10 & summed_habitat <= 16 ~ 3,
      summed_habitat > 16 & summed_habitat <= 24 ~ 4,
    )
  ) %>%
  mutate(
    final_score = case_when(
      final_score_social==4 & final_score_habitat==4 ~ 1,
      final_score_social==4 & final_score_habitat==3 ~ 2,
      final_score_social==3& final_score_habitat==4 ~ 2,
      final_score_social==3& final_score_habitat==3 ~ 3,
      final_score_social==4& final_score_habitat==2 ~ 4,
      final_score_social==4& final_score_habitat==1 ~ 4,
      final_score_social==2& final_score_habitat==4 ~ 4,
      final_score_social==1& final_score_habitat==4 ~ 4,
      final_score_social==3& final_score_habitat==NA_real_ ~ 5,
      final_score_social==NA_real_& final_score_habitat==3 ~ 5,
      final_score_social==3& final_score_habitat==2 ~ 6,
      final_score_social==2& final_score_habitat==3 ~ 6,
      final_score_social==3& final_score_habitat==1 ~ 7,
      final_score_social==1& final_score_habitat==3 ~ 7,
      final_score_social==2& final_score_habitat==2 ~ 8,
      final_score_social==2& final_score_habitat==1 ~ 9,
      final_score_social==1& final_score_habitat==2 ~ 9,
      final_score_social==1 &final_score_habitat==1 ~ 10,
      TRUE ~ NA_real_



    )
  )

final_stream <- final_stream %>% 
  mutate(across(c(waterbody_type:mussel_proximity, p_h_model:temperature_model), ~ifelse(is.na(.x), 0, .x))) %>%
  mutate(
    summed_social = waterbody_position + waterbody_size_rec + waterbody_type + mussel_proximity,
    summed_habitat = temperature_model + p_h_model + calcium_model + hardness_model + do_model + conductivity_model
  ) %>%
  mutate(
    final_score_social = case_when(
      summed_social > 0 & summed_social <= 5 ~ 1,
      summed_social > 5 & summed_social <= 10 ~ 2,
      summed_social > 10 & summed_social <= 16 ~ 3,
      summed_social > 16 & summed_social <= 24 ~ 4,
    ),
    final_score_habitat = case_when(
      summed_habitat > 0 & summed_habitat <= 5 ~ 1,
      summed_habitat > 5 & summed_habitat <= 10 ~ 2,
      summed_habitat > 10 & summed_habitat <= 16 ~ 3,
      summed_habitat > 16 & summed_habitat <= 24 ~ 4,
    )
  ) %>%
  mutate(
    final_score = case_when(
      final_score_social==4 & final_score_habitat==4 ~ 1,
      final_score_social==4 & final_score_habitat==3 ~ 2,
      final_score_social==3& final_score_habitat==4 ~ 2,
      final_score_social==3& final_score_habitat==3 ~ 3,
      final_score_social==4& final_score_habitat==2 ~ 4,
      final_score_social==4& final_score_habitat==1 ~ 4,
      final_score_social==2& final_score_habitat==4 ~ 4,
      final_score_social==1& final_score_habitat==4 ~ 4,
      final_score_social==3& final_score_habitat==NA_real_ ~ 5,
      final_score_social==NA_real_& final_score_habitat==3 ~ 5,
      final_score_social==3& final_score_habitat==2 ~ 6,
      final_score_social==2& final_score_habitat==3 ~ 6,
      final_score_social==3& final_score_habitat==1 ~ 7,
      final_score_social==1& final_score_habitat==3 ~ 7,
      final_score_social==2& final_score_habitat==2 ~ 8,
      final_score_social==2& final_score_habitat==1 ~ 9,
      final_score_social==1& final_score_habitat==2 ~ 9,
      final_score_social==1 &final_score_habitat==1 ~ 10,
      TRUE ~ NA_real_



    )
  )
myColorsFinal <- viridis::plasma(n = 10)

names(myColorsFinal) <- factor(1:10)

mapview::mapview(list(final_stream, final_lakes),
                 col.regions = myColorsFinal,
                 color = myColorsFinal,
                 zcol = 'final_score')
```


```{r disclaimer, child="DISCLAIMER.md", eval=TRUE}

```

